name: upnp_port_forward
description: upnp port forward daemon 
version: 1.0.8
homepage: https://github.com/rmw-dart/upnp_port_forward

environment:
  sdk: '>=2.15.0-178.1.beta <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  await_sleep: ^1.0.1
  collection: ^1.15.0
  intranet_ip: ^1.0.2
  random_uint8list: ^1.0.0 
  req: ^1.0.2
  rmwlog: ^1.0.2
  try_catch: ^1.0.2
  xml: ^5.3.0
